workflows:
  android-capacitor:
    name: Android Capacitor Debug Build
    max_build_duration: 60

    environment:
      node: 22
      java: 21

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build web
        script: npm run build

      - name: Sync Capacitor
        script: |
          npm run build
          npx --no-install cap sync android

      - name: Fix gradlew permissions (code 126)
        script: chmod +x android/gradlew

      - name: Build Debug APK
        script: |
          cd android
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/reports/**
